const WHATSAPP='917498169710';
const products=[
{id:1,name:'Airtight Kitchen Storage Containers – 14 Pcs.',category:'Storage',badge:'BESTSELLER',images:['assets/storage-container-1.jpeg','assets/storage-container-2.jpeg','assets/storage-container-3.jpeg','assets/storage-container-4.jpeg','assets/storage-container-5.jpeg'],image:'assets/storage-container-1.jpeg',desc:'Keep your pantry organized and food fresh for longer. BPA free, air-tight lids, durable and stackable containers.',features:['Airtight lids','BPA free','Stackable design','Clear body'],link:'https://fktr.in/A00I4I7'},
{id:2,name:'2-in-1 Oil Sprayer & Pour Bottle',category:'Kitchen',badge:'TRENDING',images:['assets/oil-sprayer-1.png','assets/oil-sprayer-2.jpeg','assets/oil-sprayer-3.jpeg','assets/oil-sprayer-4.jpeg','assets/oil-sprayer-5.jpeg','assets/oil-sprayer-6.jpeg'],image:'assets/oil-sprayer-1.png',desc:'Premium quality oil sprayer & pourer. Ideal for cooking, air frying, baking, salad, BBQ & more.',features:['Spray + pour','Fine mist','Leak-proof design','Easy to clean'],link:'https://fktr.in/BiMH68X'},
{id:3,name:'Premium Stainless Steel Bottle – 1 L',category:'Bottles',badge:'PREMIUM PICK',images:['assets/bottle-1.jpeg','assets/bottle-2.jpeg','assets/bottle-3.jpeg','assets/bottle-4.jpeg','assets/bottle-5.jpeg','assets/bottle-6.jpeg'],image:'assets/bottle-1.jpeg',desc:'Stylish 1-litre stainless steel bottle for office, gym, travelling and everyday hydration.',features:['1 Litre capacity','BPA free','Leak proof','Easy to carry','Non-toxic'],link:'https://fktr.in/l2lUkZq'},
{id:4,name:'Stainless Steel Food Storage Containers – 5 Pcs Set',category:'Storage',badge:'BESTSELLER',images:['assets/storage-set-1.jpeg','assets/storage-set-2.jpeg','assets/storage-set-3.jpeg','assets/storage-set-4.jpeg','assets/storage-set-5.jpeg'],image:'assets/storage-set-1.jpeg',desc:'Stainless steel storage set with lids for food, fruits, snacks and everyday kitchen organization.',features:['160 ml to 1000 ml','Dishwasher safe','Fridge & freezer safe','Rust free','BPA free','Made in India'],link:'https://fktr.in/tVzv2ts'},
{id:5,name:'Pigeon by Stovekraft Limited Handy Mini Vegetable & Fruit Chopper',category:'Kitchen',categoryLabel:'Kitchen / Vegetable Chopper',badge:'BESTSELLER',folder:'Pigeon by Stovekraft Limited Handy Mini Vegetable & Fruit Chopper',images:[],image:'',desc:'A handy mini chopper for quick everyday vegetable and fruit preparation.',features:['Compact design','Quick chopping','Easy everyday use','Convenient kitchen helper'],link:'https://fktr.in/6aOd3uz'},
{id:6,name:'DECORASIA Non Chemical Spoon Set for Kitchen Lovers - Wooden Measuring Spoon Set',category:'Kitchen',categoryLabel:'Kitchen / Measuring Spoons',badge:'PREMIUM PICK',folder:'DECORASIA Non Chemical Spoon Set for Kitchen Lovers - Wooden Measuring Spoon Set',images:[],image:'',desc:'A practical wooden measuring spoon set designed to make everyday kitchen measuring simple and organized.',features:['Wooden measuring spoons','Useful for baking & cooking','Easy to store','Everyday kitchen essential'],link:'https://fktr.in/L7jmpSE'},
{id:7,name:'NARIYA 360 Degree Revolving Spice Rack Set - Black',category:'Kitchen',categoryLabel:'Kitchen / Spice Storage',badge:'TRENDING',folder:'NARIYA 360 Degree Revolving Spice Rack Set - Black',images:[],image:'',desc:'Keep frequently used spices organized and within easy reach with a rotating kitchen rack.',features:['360° revolving design','Organized spice storage','Space saving','Easy access'],link:'https://fktr.in/dJ5s5ms'},
{id:8,name:'GOLDFINCH 500 ml Cooking Oil Dispenser',category:'Kitchen',categoryLabel:'Kitchen / Oil Dispenser',badge:'TRENDING',folder:'GOLDFINCH 500 ml Cooking Oil Dispenser',images:[],image:'',desc:'A practical 500 ml oil dispenser for cleaner, more controlled everyday cooking.',features:['500 ml capacity','Controlled pouring','Kitchen friendly design','Easy everyday handling'],link:'https://fktr.in/31JpkCv'},
{id:9,name:'Kitchenium Greek Yogurt & Hung Curd Maker Yogurt Maker',category:'Kitchen',categoryLabel:'Kitchen / Curd & Yogurt Maker',badge:'SMART PICK',folder:'Kitchenium Greek Yogurt & Hung Curd Maker Yogurt Maker',images:[],image:'',desc:'A simple kitchen helper for making Greek yogurt and hung curd at home.',features:['Greek yogurt maker','Hung curd preparation','Compact kitchen use','Easy to use'],link:'https://fktr.in/d6H2xpB'},
{id:10,name:'QUYZO Pack of 56 Multicolour Multipurpose Heavy-Duty Plastic Cloth Clips',category:'Home & Living',categoryLabel:'Home / Laundry',badge:'VALUE PICK',folder:'QUYZO Pack of 56 Multicolour Multipurpose Heavy-Duty Plastic Cloth Clips',images:[],image:'',desc:'A large multipurpose pack of sturdy cloth clips for everyday laundry and home organization.',features:['Pack of 56','Heavy-duty design','Multicolour','Multipurpose use'],link:'https://fktr.in/iyHyigc'},
{id:11,name:'cello Quick Boil - Lifestyle Electric Kettle',category:'Kitchen',categoryLabel:'Kitchen Electronics / Electric Kettle',badge:'BESTSELLER',folder:'cello Quick Boil - Lifestyle Electric Kettle',images:[],image:'',desc:'A convenient electric kettle for quick boiling and everyday hot-water needs.',features:['1.5 L capacity','Quick boiling','Compact countertop use','Everyday convenience'],link:'https://fktr.in/05uBEh5'},
{id:12,name:'Misuhrobir Electronic Kitchen Scale 10Kg Weighing Scale',category:'Kitchen',categoryLabel:'Kitchen Electronics / Digital Kitchen Scale',badge:'SMART PICK',folder:'Misuhrobir Electronic Kitchen Scale 10Kg Weighing Scale',images:[],image:'',desc:'A digital kitchen weighing scale for accurate everyday ingredient measurement.',features:['Up to 10 Kg capacity','Digital display','Useful for cooking & baking','Compact design'],link:'https://fktr.in/bNE0kiN'},
{id:13,name:'ACTIVA Pluto Pro 500W Mixer Grinder',category:'Kitchen',categoryLabel:'Kitchen Electronics / Mixer Grinder',badge:'BESTSELLER',folder:'ACTIVA Pluto Pro 500W Mixer Grinder',images:[],image:'',desc:'A 500W mixer grinder designed for everyday kitchen preparation with multiple jars.',features:['500W motor','3 jars','Everyday grinding','Kitchen essential'],link:'https://fktr.in/HS9pfWd'},
{id:14,name:'Mteaser Foldable Drawer Rectangular Storage Basket with Lid & Handle',category:'Storage',categoryLabel:'Home / Storage & Organization',badge:'ORGANIZE BETTER',folder:'Mteaser Foldable Drawer Rectangular Storage Basket with Lid & Handle',images:[],image:'',desc:'Foldable storage baskets with lid and handle to keep clothes and household items neatly organized.',features:['Foldable design','Lid included','Easy-carry handle','Space-saving storage'],link:'https://fktr.in/58K5z5g'},
{id:15,name:'Beco Max Kitchen Cleaner',category:'Home & Living',categoryLabel:'Home Cleaning / Kitchen Cleaner',badge:'TRENDING',folder:'Beco Max Kitchen Cleaner',images:[],image:'',desc:'A kitchen cleaner made to tackle grease, oil, curry and tough kitchen stains.',features:['Grease removal','Tough stain cleaning','Kitchen focused formula','Easy spray application'],link:'https://fktr.in/eNqB2g0'},
{id:16,name:'CAMPUS HURRICANE Running Shoes for Men',category:'Lifestyle',categoryLabel:"Lifestyle / Men's Footwear",badge:'TRENDING',folder:'CAMPUS HURRICANE Running Shoes for Men',images:[],image:'',desc:'Comfort-focused running shoes suitable for running, walking and everyday active use.',features:['Breathable mesh','Memory foam comfort','Anti-slip grip','Running & everyday use'],link:'https://fktr.in/0sW8XPO'}
];
let active='All';let cart=JSON.parse(localStorage.getItem('shambhoCartV6')||'[]');
const grid=document.getElementById('productGrid');
const FALLBACK='assets/product-placeholder.svg';
function render(){const list=active==='All'?products:products.filter(p=>p.category===active);grid.innerHTML=list.map(p=>`<article class="product"><div class="product-img"><span class="badge">${p.badge}</span><img src="${p.image||FALLBACK}" alt="${p.name}" loading="lazy"></div><div class="product-info"><div class="product-cat">${p.categoryLabel||p.category}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="actions"><button class="details" onclick="showProduct(${p.id})">View Details</button><button class="enquiry" onclick="ask(${p.id})">Enquiry</button></div></div></article>`).join('')}
function setFilter(f){active=f;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));render()}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));
document.querySelectorAll('[data-filter-link]').forEach(a=>a.onclick=e=>{e.preventDefault();setFilter(a.dataset.filterLink);document.getElementById('shop').scrollIntoView({behavior:'smooth'});});
document.getElementById('searchBtn').onclick=()=>{const q=document.getElementById('searchInput').value.toLowerCase().trim();if(!q){setFilter('All');return}const list=products.filter(p=>(p.name+' '+p.category+' '+(p.categoryLabel||'')+' '+p.desc).toLowerCase().includes(q));grid.innerHTML=list.map(p=>`<article class="product"><div class="product-img"><span class="badge">${p.badge}</span><img src="${p.image||FALLBACK}" alt="${p.name}" loading="lazy"></div><div class="product-info"><div class="product-cat">${p.categoryLabel||p.category}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="actions"><button class="details" onclick="showProduct(${p.id})">View Details</button><button class="enquiry" onclick="ask(${p.id})">Enquiry</button></div></div></article>`).join('')||'<p>No matching products found.</p>';document.getElementById('shop').scrollIntoView({behavior:'smooth'});};
document.getElementById('categorySelect').onchange=e=>setFilter(e.target.value);
function ask(id){const p=products.find(x=>x.id===id);window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent('Hi ShambhoMART, I am interested in "'+p.name+'". Please share current details and offer.')}`,'_blank')}
function showProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const imgs=(p.images&&p.images.length?p.images:[p.image||FALLBACK]).filter(Boolean);const body=document.getElementById('modalBody');body.innerHTML=`<div class="modal-content"><div class="gallery"><div class="gallery-main" id="galleryZoomBox"><img id="galleryMain" src="${imgs[0]}" alt="${p.name}"></div><div class="gallery-zoom-hint">Move cursor over image to zoom • Click to lock</div><div class="gallery-count">${imgs.length} product images</div><div class="gallery-thumbs" id="galleryThumbs">${imgs.map((src,i)=>`<button type="button" class="gallery-thumb ${i===0?'active':''}" data-src="${src}" aria-label="Product image ${i+1}"><img src="${src}" alt="${p.name} view ${i+1}" loading="lazy"></button>`).join('')}</div></div><div class="product-detail-copy"><div class="eyebrow">${p.badge} • ${p.categoryLabel||p.category}</div><h2>${p.name}</h2><p>${p.desc}</p><ul>${p.features.map(f=>`<li>✓ ${f}</li>`).join('')}</ul><p><strong>Price:</strong> Check current offer on the partner store. We intentionally do not show fixed prices because offers can change.</p><div class="detail-actions"><a href="${p.link}" target="_blank" rel="noopener sponsored">Shop Now →</a><a class="wa" href="https://wa.me/${WHATSAPP}?text=${encodeURIComponent('Hi ShambhoMART, I want details for '+p.name)}" target="_blank" rel="noopener">WhatsApp Enquiry</a></div></div></div>`;const thumbs=document.getElementById('galleryThumbs');thumbs.addEventListener('click',e=>{const btn=e.target.closest('.gallery-thumb');if(!btn)return;const main=document.getElementById('galleryMain');main.src=btn.dataset.src;document.querySelectorAll('.gallery-thumb').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const box=document.getElementById('galleryZoomBox');box.classList.remove('zoom-locked','zoom-hover');main.style.transformOrigin='center center'});const box=document.getElementById('galleryZoomBox');const main=document.getElementById('galleryMain');box.addEventListener('mousemove',e=>{const r=box.getBoundingClientRect();const x=Math.max(0,Math.min(100,((e.clientX-r.left)/r.width)*100));const y=Math.max(0,Math.min(100,((e.clientY-r.top)/r.height)*100));main.style.transformOrigin=`${x}% ${y}%`;box.classList.add('zoom-hover')});box.addEventListener('mouseleave',()=>{if(!box.classList.contains('zoom-locked'))box.classList.remove('zoom-hover')});box.addEventListener('click',()=>box.classList.toggle('zoom-locked'));box.addEventListener('dblclick',()=>openExploded(main.src,p.name));document.getElementById('modal').classList.add('show');document.body.classList.add('modal-open')}
function openExploded(src,name){let viewer=document.getElementById('explodedViewer');if(!viewer){viewer=document.createElement('div');viewer.id='explodedViewer';viewer.className='exploded-viewer';viewer.innerHTML='<button class="exploded-close" aria-label="Close">×</button><div class="exploded-image-box"><img id="explodedImage" alt=""><div class="exploded-hint">Move cursor over image to zoom • Click to lock</div></div>';document.body.appendChild(viewer);const close=()=>{viewer.classList.remove('show');document.body.classList.remove('exploded-open')};viewer.querySelector('.exploded-close').onclick=close;viewer.onclick=e=>{if(e.target===viewer)close()};const eb=viewer.querySelector('.exploded-image-box'),ei=viewer.querySelector('#explodedImage');eb.addEventListener('mousemove',e=>{const r=eb.getBoundingClientRect();const x=Math.max(0,Math.min(100,((e.clientX-r.left)/r.width)*100));const y=Math.max(0,Math.min(100,((e.clientY-r.top)/r.height)*100));ei.style.transformOrigin=`${x}% ${y}%`;eb.classList.add('zoom-hover')});eb.addEventListener('mouseleave',()=>{if(!eb.classList.contains('zoom-locked'))eb.classList.remove('zoom-hover')});eb.addEventListener('click',()=>eb.classList.toggle('zoom-locked'));document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}viewer.querySelector('#explodedImage').src=src;viewer.querySelector('#explodedImage').alt=name;viewer.querySelector('.exploded-image-box').classList.remove('zoom-hover','zoom-locked');viewer.classList.add('show');document.body.classList.add('exploded-open')}
document.getElementById('closeModal').onclick=()=>{document.getElementById('modal').classList.remove('show');document.body.classList.remove('modal-open')};document.getElementById('modal').onclick=e=>{if(e.target.id==='modal'){e.currentTarget.classList.remove('show');document.body.classList.remove('modal-open')}};
function updateCart(){document.getElementById('cartCount').textContent=cart.length;const box=document.getElementById('cartItems');box.innerHTML=cart.length?cart.map((id,i)=>{const p=products.find(x=>x.id===id);return `<div class="cart-item"><img src="${p.image||FALLBACK}" alt=""><div><h4>${p.name}</h4><small>${p.categoryLabel||p.category}</small></div><button class="remove" onclick="cart.splice(${i},1);saveCart()">Remove</button></div>`}).join(''):'<p style="padding:20px;color:#667085">Your selection is empty.</p>'}
function saveCart(){localStorage.setItem('shambhoCartV6',JSON.stringify(cart));updateCart()}
document.getElementById('cartBtn').onclick=()=>{document.getElementById('cartDrawer').classList.add('open');document.getElementById('overlay').classList.add('show')};document.getElementById('closeCart').onclick=closeCart;document.getElementById('overlay').onclick=closeCart;function closeCart(){document.getElementById('cartDrawer').classList.remove('open');document.getElementById('overlay').classList.remove('show')};document.getElementById('whatsappOrder').onclick=()=>{if(!cart.length)return alert('Please add products first.');const names=cart.map(id=>products.find(p=>p.id===id).name);window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent('Hi ShambhoMART, I want to enquire/order these products:\n\n• '+names.join('\n• '))}`,'_blank')};document.getElementById('clearCart').onclick=()=>{cart=[];saveCart()};
async function loadProductImages(){try{const res=await fetch('assets/IMAGE_MANIFEST.json',{cache:'no-store'});if(!res.ok)throw new Error('Image manifest unavailable');const manifest=await res.json();const grouped={};manifest.forEach(item=>{const parts=item.optimized.split('/');const folder=parts.shift();const path='assets/'+item.optimized;(grouped[folder]??=[]).push(path)});Object.entries(grouped).forEach(([folder,imgs])=>{const p=products.find(x=>x.folder===folder);if(!p)return;const sorted=[...imgs].sort((a,b)=>{const an=a.split('/').pop().toLowerCase(),bn=b.split('/').pop().toLowerCase();const ap=an.startsWith('pr')?0:1,bp=bn.startsWith('pr')?0:1;if(ap!==bp)return ap-bp;return an.localeCompare(bn,undefined,{numeric:true})});p.images=sorted;p.image=sorted[0]||FALLBACK});}catch(err){console.warn('Product image manifest could not be loaded:',err)}render();updateCart()}
document.getElementById('year').textContent=new Date().getFullYear();loadProductImages();
